In [1]:
import pandas as pd

In [2]:
chartevent = pd.read_csv('chartevents.csv', nrows = 2000)
discharge = pd.read_csv('discharge.csv', nrows = 2000)
microbiologyevent = pd.read_csv('microbiologyevents.csv', nrows = 2000)
procedureevent = pd.read_csv('procedureevents.csv', nrows = 2000)
radiologyevent = pd.read_csv('radiology_detail.csv', nrows = 2000)

In [10]:
labevent = pd.read_csv('labevents.csv', nrows = 2000)

In [3]:
chartevent.head(100)

,subject_id,hadm_id,stay_id,caregiver_id,charttime,storetime,itemid,value,valuenum,valueuom,warning
0,10000032,29079034,39553978,18704.0,2180-07-23 12:36:00,2180-07-23 14:45:00,226512,39.4,39.4,kg,0.0
1,10000032,29079034,39553978,18704.0,2180-07-23 12:36:00,2180-07-23 14:45:00,226707,60,60.0,Inch,0.0
2,10000032,29079034,39553978,18704.0,2180-07-23 12:36:00,2180-07-23 14:45:00,226730,152,152.0,cm,0.0
3,10000032,29079034,39553978,18704.0,2180-07-23 14:00:00,2180-07-23 14:18:00,220048,SR (Sinus Rhythm),NaN,NaN,0.0
4,10000032,29079034,39553978,18704.0,2180-07-23 14:00:00,2180-07-23 14:18:00,224642,Oral,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...
95,10000032,29079034,39553978,18704.0,2180-07-23 14:30:00,2180-07-23 14:43:00,220048,SR (Sinus Rhythm),NaN,NaN,0.0
96,10000032,29079034,39553978,18704.0,2180-07-23 14:30:00,2180-07-23 14:43:00,220179,95,95.0,mmHg,0.0
97,10000032,29079034,39553978,18704.0,2180-07-23 14:30:00,2180-07-23 14:43:00,220180,59,59.0,mmHg,0.0
98,10000032,29079034,39553978,18704.0,2180-07-23 14:30:00,2180-07-23 14:43:00,220181,67,67.0,mmHg,0.0
99,10000032,29079034,39553978,18704.0,2180-07-23 14:30:00,2180-07-23 14:43:00,220210,21,21.0,insp/min,0.0

In [4]:
# Lọc các itemid bị trùng (giữ tất cả các dòng trùng)
dup_items = chartevent[chartevent.duplicated(subset='itemid', keep=False)]

dup_items

,subject_id,hadm_id,stay_id,caregiver_id,charttime,storetime,itemid,value,valuenum,valueuom,warning
0,10000032,29079034,39553978,18704.0,2180-07-23 12:36:00,2180-07-23 14:45:00,226512,39.4,39.4,kg,0.0
3,10000032,29079034,39553978,18704.0,2180-07-23 14:00:00,2180-07-23 14:18:00,220048,SR (Sinus Rhythm),NaN,NaN,0.0
4,10000032,29079034,39553978,18704.0,2180-07-23 14:00:00,2180-07-23 14:18:00,224642,Oral,NaN,NaN,0.0
5,10000032,29079034,39553978,18704.0,2180-07-23 14:00:00,2180-07-23 14:18:00,224650,NaN,NaN,NaN,0.0
6,10000032,29079034,39553978,18704.0,2180-07-23 14:00:00,2180-07-23 14:20:00,223761,98.7,98.7,°F,0.0
...,...,...,...,...,...,...,...,...,...,...,...
1995,10000690,25860671,37081114,33125.0,2150-11-03 16:00:00,2150-11-03 16:39:00,224945,Rash,NaN,NaN,0.0
1996,10000690,25860671,37081114,33125.0,2150-11-03 16:00:00,2150-11-03 16:39:00,224959,Pink,NaN,NaN,0.0
1997,10000690,25860671,37081114,33125.0,2150-11-03 16:34:00,2150-11-03 16:34:00,223834,4,4.0,L/min,0.0
1998,10000690,25860671,37081114,33125.0,2150-11-03 16:34:00,2150-11-03 16:34:00,226732,Nasal cannula,NaN,NaN,0.0
1999,10000690,25860671,37081114,33125.0,2150-11-03 16:38:00,2150-11-03 16:38:00,225234,WNL,NaN,NaN,0.0

In [5]:
chartevent[chartevent['itemid'] == 220210]

,subject_id,hadm_id,stay_id,caregiver_id,charttime,storetime,itemid,value,valuenum,valueuom,warning
11,10000032,29079034,39553978,18704.0,2180-07-23 14:12:00,2180-07-23 14:17:00,220210,24,24.0,insp/min,0.0
99,10000032,29079034,39553978,18704.0,2180-07-23 14:30:00,2180-07-23 14:43:00,220210,21,21.0,insp/min,0.0
165,10000032,29079034,39553978,18704.0,2180-07-23 15:00:00,2180-07-23 15:34:00,220210,23,23.0,insp/min,0.0
179,10000032,29079034,39553978,18704.0,2180-07-23 16:00:00,2180-07-23 16:05:00,220210,21,21.0,insp/min,0.0
210,10000032,29079034,39553978,18704.0,2180-07-23 17:00:00,2180-07-23 17:01:00,220210,20,20.0,insp/min,0.0
252,10000032,29079034,39553978,18704.0,2180-07-23 18:00:00,2180-07-23 18:16:00,220210,21,21.0,insp/min,0.0
313,10000032,29079034,39553978,20925.0,2180-07-23 19:00:00,2180-07-23 19:59:00,220210,16,16.0,insp/min,0.0
324,10000032,29079034,39553978,20925.0,2180-07-23 20:00:00,2180-07-23 21:01:00,220210,19,19.0,insp/min,0.0
362,10000032,29079034,39553978,20925.0,2180-07-23 21:00:00,2180-07-23 21:01:00,220210,22,22.0,insp/min,0.0
463,10000032,29079034,39553978,76052.0,2180-07-23 22:00:00,2180-07-23 22:15:00,220210,20,20.0,insp/min,0.0
505,10000690,25860671,37081114,8787.0,2150-11-06 08:00:00,2150-11-06 09:07:00,220210,23,23.0,insp/min,0.0
672,10000690,25860671,37081114,8787.0,2150-11-06 09:00:00,2150-11-06 09:07:00,220210,26,26.0,insp/min,0.0
686,10000690,25860671,37081114,8787.0,2150-11-06 10:00:00,2150-11-06 13:15:00,220210,27,27.0,insp/min,0.0
697,10000690,25860671,37081114,8787.0,2150-11-06 11:00:00,2150-11-06 13:15:00,220210,25,25.0,insp/min,0.0
708,10000690,25860671,37081114,8787.0,2150-11-06 12:00:00,2150-11-06 13:15:00,220210,23,23.0,insp/min,0.0
842,10000690,25860671,37081114,8787.0,2150-11-06 13:00:00,2150-11-06 13:15:00,220210,20,20.0,insp/min,0.0
850,10000690,25860671,37081114,8787.0,2150-11-06 14:00:00,2150-11-06 14:12:00,220210,29,29.0,insp/min,0.0
860,10000690,25860671,37081114,9137.0,2150-11-06 15:00:00,2150-11-06 16:11:00,220210,26,26.0,insp/min,0.0
867,10000690,25860671,37081114,9137.0,2150-11-06 16:00:00,2150-11-06 16:11:00,220210,26,26.0,insp/min,0.0
1008,10000690,25860671,37081114,17393.0,2150-11-02 19:54:00,2150-11-02 20:12:00,220210,23,23.0,insp/min,0.0
1014,10000690,25860671,37081114,17393.0,2150-11-02 20:00:00,2150-11-02 20:12:00,220210,23,23.0,insp/min,0.0
1034,10000690,25860671,37081114,17393.0,2150-11-02 20:12:00,2150-11-02 20:12:00,220210,27,27.0,insp/min,0.0
1140,10000690,25860671,37081114,17393.0,2150-11-02 21:00:00,2150-11-02 21:26:00,220210,26,26.0,insp/min,0.0
1149,10000690,25860671,37081114,17393.0,2150-11-02 22:00:00,2150-11-02 22:08:00,220210,20,20.0,insp/min,0.0
1155,10000690,25860671,37081114,17393.0,2150-11-02 23:00:00,2150-11-02 23:11:00,220210,19,19.0,insp/min,0.0
1165,10000690,25860671,37081114,17393.0,2150-11-03 00:00:00,2150-11-03 00:41:00,220210,21,21.0,insp/min,0.0
1269,10000690,25860671,37081114,17393.0,2150-11-03 01:00:00,2150-11-03 01:16:00,220210,22,22.0,insp/min,0.0
1282,10000690,25860671,37081114,17393.0,2150-11-03 02:00:00,2150-11-03 02:06:00,220210,27,27.0,insp/min,0.0
1308,10000690,25860671,37081114,17393.0,2150-11-03 03:00:00,2150-11-03 04:29:00,220210,20,20.0,insp/min,0.0
1317,10000690,25860671,37081114,17393.0,2150-11-03 04:00:00,2150-11-03 04:29:00,220210,21,21.0,insp/min,0.0
1446,10000690,25860671,37081114,17393.0,2150-11-03 05:00:00,2150-11-03 05:03:00,220210,24,24.0,insp/min,0.0
1460,10000690,25860671,37081114,17393.0,2150-11-03 06:00:00,2150-11-03 06:59:00,220210,21,21.0,insp/min,0.0
1469,10000690,25860671,37081114,33125.0,2150-11-03 08:00:00,2150-11-03 09:04:00,220210,26,26.0,insp/min,0.0
1644,10000690,25860671,37081114,33125.0,2150-11-03 09:00:00,2150-11-03 09:04:00,220210,23,23.0,insp/min,0.0
1669,10000690,25860671,37081114,33125.0,2150-11-03 10:00:00,2150-11-03 10:08:00,220210,20,20.0,insp/min,0.0
1680,10000690,25860671,37081114,33125.0,2150-11-03 11:00:00,2150-11-03 11:02:00,220210,18,18.0,insp/min,0.0
1814,10000690,25860671,37081114,33125.0,2150-11-03 12:00:00,2150-11-03 12:31:00,220210,30,30.0,insp/min,0.0
1828,10000690,25860671,37081114,33125.0,2150-11-03 13:00:00,2150-11-03 14:11:00,220210,19,19.0,insp/min,0.0
1855,10000690,25860671,37081114,33125.0,2150-11-03 14:00:00,2150-11-03 14:11:00,220210,17,17.0,insp/min,0.0
1866,10000690,25860671,37081114,33125.0,2150-11-03 15:00:00,2150-11-03 15:15:00,220210,17,17.0,insp/min,0.0
1875,10000690,25860671,37081114,33125.0,2150-11-03 16:00:00,2150-11-03 16:33:00,220210,16,16.0,insp/min,0.0

In [6]:
discharge.head(100)

,note_id,subject_id,hadm_id,note_type,note_seq,charttime,storetime,text
0,10000032-DS-21,10000032,22595853,DS,21,2180-05-07 00:00:00,2180-05-09 15:26:00,\nName: ___ Unit No: _...
1,10000032-DS-22,10000032,22841357,DS,22,2180-06-27 00:00:00,2180-07-01 10:15:00,\nName: ___ Unit No: _...
2,10000032-DS-23,10000032,29079034,DS,23,2180-07-25 00:00:00,2180-07-25 21:42:00,\nName: ___ Unit No: _...
3,10000032-DS-24,10000032,25742920,DS,24,2180-08-07 00:00:00,2180-08-10 05:43:00,\nName: ___ Unit No: _...
4,10000084-DS-17,10000084,23052089,DS,17,2160-11-25 00:00:00,2160-11-25 15:09:00,\nName: ___ Unit No: __...
...,...,...,...,...,...,...,...,...
95,10002430-DS-7,10002430,26295318,DS,7,2129-06-24 00:00:00,2129-06-24 16:51:00,\nName: ___ Unit No: ___\n \n...
96,10002443-DS-15,10002443,21329021,DS,15,2183-10-20 00:00:00,2183-10-20 19:18:00,\nName: ___ Unit No: ...
97,10002495-DS-13,10002495,24982426,DS,13,2141-05-29 00:00:00,2141-05-30 02:29:00,\nName: ___ Unit No: ___\...
98,10002528-DS-17,10002528,23193578,DS,17,2168-12-20 00:00:00,2168-12-20 17:28:00,\nName: ___ Unit No: ___\n...
99,10002528-DS-18,10002528,28605730,DS,18,2170-03-18 00:00:00,2170-03-18 16:39:00,\nName: ___ Unit No: ___\n...

In [8]:
microbiologyevent.head(100)

,microevent_id,subject_id,hadm_id,micro_specimen_id,order_provider_id,chartdate,charttime,spec_itemid,spec_type_desc,test_seq,...,org_name,isolate_num,quantity,ab_itemid,ab_name,dilution_text,dilution_comparison,dilution_value,interpretation,comments
0,1,10000032,NaN,1304715,P69FQC,2180-03-23 00:00:00,2180-03-23 11:51:00,70046,IMMUNOLOGY,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,___
1,2,10000032,NaN,3342526,P69FQC,2180-03-23 00:00:00,2180-03-23 11:51:00,70093,Blood (Toxo),1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NEGATIVE FOR TOXOPLASMA IgG ANTIBODY BY EIA. ...
2,3,10000032,NaN,3910370,P69FQC,2180-03-23 00:00:00,2180-03-23 11:51:00,70017,SEROLOGY/BLOOD,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NONREACTIVE. Reference Range: Non-Reactive.
3,4,10000032,NaN,5401234,P69FQC,2180-03-23 00:00:00,2180-03-23 11:51:00,70017,SEROLOGY/BLOOD,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POSITIVE BY EIA. A positive IgG result genera...
4,5,10000032,NaN,6287540,P69FQC,2180-03-23 00:00:00,2180-03-23 11:51:00,70046,IMMUNOLOGY,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HIV-1 RNA is not detected. Performed using th...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,10000635,NaN,3803904,NaN,2143-12-23 00:00:00,2143-12-23 10:41:00,70079,URINE,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"MIXED BACTERIAL FLORA ( >= 3 COLONY TYPES), CO..."
96,97,10000650,NaN,9604733,NaN,2142-08-03 00:00:00,2142-08-03 21:45:00,70017,SEROLOGY/BLOOD,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NEGATIVE by Latex Agglutination. (R...
97,98,10000690,NaN,2595393,P25B6Q,2149-08-09 00:00:00,2149-08-09 16:56:00,70070,SWAB,1,...,STAPH AUREUS COAG +,1.0,NaN,90003.0,PENICILLIN G,=>0.5,=>,0.5,R,NaN
98,99,10000690,NaN,2595393,P25B6Q,2149-08-09 00:00:00,2149-08-09 16:56:00,70070,SWAB,1,...,STAPH AUREUS COAG +,1.0,NaN,90006.0,ERYTHROMYCIN,=>8,=>,8.0,R,NaN
99,100,10000690,NaN,2595393,P25B6Q,2149-08-09 00:00:00,2149-08-09 16:56:00,70070,SWAB,1,...,STAPH AUREUS COAG +,1.0,NaN,90007.0,CLINDAMYCIN,=>8,=>,8.0,R,NaN

In [9]:
procedureevent.head(100)

,subject_id,hadm_id,stay_id,caregiver_id,starttime,endtime,storetime,itemid,value,valueuom,...,orderid,linkorderid,ordercategoryname,ordercategorydescription,patientweight,isopenbag,continueinnextdept,statusdescription,originalamount,originalrate
0,10000032,29079034,39553978,18704.0,2180-07-23 14:43:00,2180-07-23 14:44:00,2180-07-23 14:43:00,225966,1.0,NaN,...,3050203,3050203,Procedures,Task,39.4,0,0,FinishedRunning,1.0,0
1,10000032,29079034,39553978,NaN,2180-07-23 14:24:00,2180-07-23 23:50:00,2180-07-23 23:50:49.983,224275,566.0,min,...,769190,769190,Peripheral Lines,ContinuousProcess,39.4,1,0,FinishedRunning,566.0,1
2,10000032,29079034,39553978,NaN,2180-07-23 14:24:00,2180-07-23 23:50:00,2180-07-23 23:50:49.983,224277,566.0,min,...,2668055,2668055,Peripheral Lines,ContinuousProcess,39.4,1,0,FinishedRunning,566.0,1
3,10000690,25860671,37081114,17393.0,2150-11-02 20:00:00,2150-11-03 13:00:00,2150-11-03 14:50:00,224275,1020.0,min,...,301419,301419,Peripheral Lines,ContinuousProcess,55.3,1,0,FinishedRunning,1020.0,1
4,10000690,25860671,37081114,17393.0,2150-11-02 20:38:00,2150-11-03 11:59:00,2150-11-03 12:34:00,224277,921.0,min,...,5207974,5207974,Peripheral Lines,ContinuousProcess,55.3,1,0,FinishedRunning,921.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,10002428,23473524,35479615,31884.0,2156-05-11 17:51:00,2156-05-14 13:00:00,2156-05-14 13:11:00,224277,4029.0,min,...,6684970,6684970,Peripheral Lines,ContinuousProcess,48.4,1,0,FinishedRunning,4029.0,1
96,10002428,23473524,35479615,31884.0,2156-05-11 17:51:00,2156-05-15 20:40:00,2156-05-15 20:41:00,225752,5929.0,min,...,4038005,4038005,Invasive Lines,ContinuousProcess,48.4,1,0,FinishedRunning,5929.0,1
97,10002428,23473524,35479615,31884.0,2156-05-11 17:52:00,2156-05-11 17:53:00,2156-05-11 17:52:00,221216,1.0,NaN,...,5033970,5033970,Imaging,Task,48.4,0,0,FinishedRunning,1.0,0
98,10002428,23473524,35479615,31884.0,2156-05-11 17:52:00,2156-05-11 17:53:00,2156-05-11 17:52:00,225966,1.0,NaN,...,9330805,9330805,Procedures,Task,48.4,0,0,FinishedRunning,1.0,0
99,10002428,23473524,35479615,31884.0,2156-05-11 19:19:00,2156-05-15 10:51:00,2156-05-15 10:50:00,225204,5252.0,min,...,2989118,2989118,Invasive Lines,ContinuousProcess,48.4,1,0,FinishedRunning,5252.0,1

In [11]:
labevent.head(100)

,labevent_id,subject_id,hadm_id,specimen_id,itemid,order_provider_id,charttime,storetime,value,valuenum,valueuom,ref_range_lower,ref_range_upper,flag,priority,comments
0,1,10000032,NaN,2704548,50931,P69FQC,2180-03-23 11:51:00,2180-03-23 15:56:00,___,95.0,mg/dL,70.0,100.0,NaN,ROUTINE,"IF FASTING, 70-100 NORMAL, >125 PROVISIONAL DI..."
1,2,10000032,NaN,36092842,51071,P69FQC,2180-03-23 11:51:00,2180-03-23 16:00:00,NEG,NaN,NaN,NaN,NaN,NaN,ROUTINE,NaN
2,3,10000032,NaN,36092842,51074,P69FQC,2180-03-23 11:51:00,2180-03-23 16:00:00,NEG,NaN,NaN,NaN,NaN,NaN,ROUTINE,NaN
3,4,10000032,NaN,36092842,51075,P69FQC,2180-03-23 11:51:00,2180-03-23 16:00:00,NEG,NaN,NaN,NaN,NaN,NaN,ROUTINE,BENZODIAZEPINE IMMUNOASSAY SCREEN DOES NOT DET...
4,5,10000032,NaN,36092842,51079,P69FQC,2180-03-23 11:51:00,2180-03-23 16:00:00,NEG,NaN,NaN,NaN,NaN,NaN,ROUTINE,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,10000032,NaN,95700408,50861,NaN,2180-05-06 22:25:00,2180-05-06 23:16:00,100,100.0,IU/L,0.0,40.0,abnormal,STAT,NaN
96,97,10000032,NaN,95700408,50862,NaN,2180-05-06 22:25:00,2180-05-06 23:16:00,3.3,3.3,g/dL,3.5,5.2,abnormal,STAT,NaN
97,98,10000032,NaN,95700408,50863,NaN,2180-05-06 22:25:00,2180-05-06 23:16:00,114,114.0,IU/L,35.0,105.0,abnormal,STAT,NaN
98,99,10000032,NaN,95700408,50868,NaN,2180-05-06 22:25:00,2180-05-06 23:16:00,9,9.0,mEq/L,8.0,20.0,NaN,STAT,NaN
99,100,10000032,NaN,95700408,50878,NaN,2180-05-06 22:25:00,2180-05-06 23:16:00,114,114.0,IU/L,0.0,40.0,abnormal,STAT,NaN

In [12]:
radiologyevent.head(100)

,note_id,subject_id,field_name,field_value,field_ordinal
0,10000032-RR-14,10000032,exam_code,C11,1
1,10000032-RR-14,10000032,exam_name,CHEST (PA & LAT),1
2,10000032-RR-15,10000032,exam_code,U314,1
3,10000032-RR-15,10000032,exam_code,U644,3
4,10000032-RR-15,10000032,exam_code,W82,2
...,...,...,...,...,...
95,10000117-RR-25,10000117,exam_code,E212L,1
96,10000117-RR-25,10000117,exam_name,HIP UNILAT MIN 2 VIEWS LEFT,1
97,10000117-RR-26,10000117,exam_code,E212L,1
98,10000117-RR-26,10000117,exam_name,HIP UNILAT MIN 2 VIEWS LEFT,1
99,10000117-RR-27,10000117,exam_code,E212L,1

In [13]:
print(chartevent.columns)

Index(['subject_id', 'hadm_id', 'stay_id', 'caregiver_id', 'charttime',
       'storetime', 'itemid', 'value', 'valuenum', 'valueuom', 'warning'],
      dtype='object')

In [14]:
print(discharge.columns)

Index(['note_id', 'subject_id', 'hadm_id', 'note_type', 'note_seq',
       'charttime', 'storetime', 'text'],
      dtype='object')

In [15]:
print(labevent.columns)

Index(['labevent_id', 'subject_id', 'hadm_id', 'specimen_id', 'itemid',
       'order_provider_id', 'charttime', 'storetime', 'value', 'valuenum',
       'valueuom', 'ref_range_lower', 'ref_range_upper', 'flag', 'priority',
       'comments'],
      dtype='object')

In [16]:
print(microbiologyevent.columns)

Index(['microevent_id', 'subject_id', 'hadm_id', 'micro_specimen_id',
       'order_provider_id', 'chartdate', 'charttime', 'spec_itemid',
       'spec_type_desc', 'test_seq', 'storedate', 'storetime', 'test_itemid',
       'test_name', 'org_itemid', 'org_name', 'isolate_num', 'quantity',
       'ab_itemid', 'ab_name', 'dilution_text', 'dilution_comparison',
       'dilution_value', 'interpretation', 'comments'],
      dtype='object')

In [17]:
print(procedureevent.columns)

Index(['subject_id', 'hadm_id', 'stay_id', 'caregiver_id', 'starttime',
       'endtime', 'storetime', 'itemid', 'value', 'valueuom', 'location',
       'locationcategory', 'orderid', 'linkorderid', 'ordercategoryname',
       'ordercategorydescription', 'patientweight', 'isopenbag',
       'continueinnextdept', 'statusdescription', 'originalamount',
       'originalrate'],
      dtype='object')

In [18]:
print(radiologyevent.columns)

Index(['note_id', 'subject_id', 'field_name', 'field_value', 'field_ordinal'], dtype='object')

In [30]:
import pandas as pd

mapping_rows = [
    # ===== CHARTEVENTS =====
    {
        "variable_name": "Nhiệt độ",
        "source_table": "chartevents",
        "lookup_column": "itemid",
        "lookup_value": 223761,
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "valuenum",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": "stay_id",
        "note_id_column": None,
    },
    {
        "variable_name": "Nhiệt độ",
        "source_table": "chartevents",
        "lookup_column": "itemid",
        "lookup_value": 223762,
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "valuenum",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": "stay_id",
        "note_id_column": None,
    },
    {
        "variable_name": "Ho",
        "source_table": "chartevents",
        "lookup_column": "itemid",
        "lookup_value": 223991,
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "value",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": "stay_id",
        "note_id_column": None,
    },
    {
        "variable_name": "Ho",
        "source_table": "chartevents",
        "lookup_column": "itemid",
        "lookup_value": 223992,
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "value",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": "stay_id",
        "note_id_column": None,
    },
    {
        "variable_name": "Đờm mủ",
        "source_table": "chartevents",
        "lookup_column": "itemid",
        "lookup_value": 224370,
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "value",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": "stay_id",
        "note_id_column": None,
    },
    {
        "variable_name": "Nhịp thở",
        "source_table": "chartevents",
        "lookup_column": "itemid",
        "lookup_value": 230042,
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "valuenum",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": "stay_id",
        "note_id_column": None,
    },
    {
        "variable_name": "SpO2",
        "source_table": "chartevents",
        "lookup_column": "itemid",
        "lookup_value": 220277,
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "valuenum",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": "stay_id",
        "note_id_column": None,
    },
    {
        "variable_name": "Cần hỗ trợ oxy",
        "source_table": "chartevents",
        "lookup_column": "itemid",
        "lookup_value": 226732,
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "value",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": "stay_id",
        "note_id_column": None,
    },
    {
        "variable_name": "FiO2",
        "source_table": "chartevents",
        "lookup_column": "itemid",
        "lookup_value": 223835,
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "valuenum",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": "stay_id",
        "note_id_column": None,
    },
    {
        "variable_name": "Rale",
        "source_table": "chartevents",
        "lookup_column": "itemid",
        "lookup_value": 223986,
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "value",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": "stay_id",
        "note_id_column": None,
    },
    {
        "variable_name": "Rale",
        "source_table": "chartevents",
        "lookup_column": "itemid",
        "lookup_value": 223987,
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "value",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": "stay_id",
        "note_id_column": None,
    },
    {
        "variable_name": "Rale",
        "source_table": "chartevents",
        "lookup_column": "itemid",
        "lookup_value": 223988,
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "value",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": "stay_id",
        "note_id_column": None,
    },
    {
        "variable_name": "Rale",
        "source_table": "chartevents",
        "lookup_column": "itemid",
        "lookup_value": 223989,
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "value",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": "stay_id",
        "note_id_column": None,
    },
    {
        "variable_name": "Tiếng thở phế quản",
        "source_table": "chartevents",
        "lookup_column": "itemid",
        "lookup_value": 223986,
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "value",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": "stay_id",
        "note_id_column": None,
    },
    {
        "variable_name": "Tiếng thở phế quản",
        "source_table": "chartevents",
        "lookup_column": "itemid",
        "lookup_value": 223987,
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "value",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": "stay_id",
        "note_id_column": None,
    },
    {
        "variable_name": "Tiếng thở phế quản",
        "source_table": "chartevents",
        "lookup_column": "itemid",
        "lookup_value": 223988,
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "value",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": "stay_id",
        "note_id_column": None,
    },
    {
        "variable_name": "Tiếng thở phế quản",
        "source_table": "chartevents",
        "lookup_column": "itemid",
        "lookup_value": 223989,
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "value",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": "stay_id",
        "note_id_column": None,
    },
    {
        "variable_name": "Huyết áp tâm thu",
        "source_table": "chartevents",
        "lookup_column": "itemid",
        "lookup_value": 220179,
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "valuenum",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": "stay_id",
        "note_id_column": None,
    },

    # ===== LABEVENTS =====
    {
        "variable_name": "Bạch cầu niệu",
        "source_table": "labevents",
        "lookup_column": "itemid",
        "lookup_value": 51516,
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "valuenum",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": None,
        "note_id_column": None,
    },
    {
        "variable_name": "Mủ niệu",
        "source_table": "labevents",
        "lookup_column": "itemid",
        "lookup_value": 51516,
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "valuenum",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": None,
        "note_id_column": None,
    },
    {
        "variable_name": "Nitrat niệu",
        "source_table": "labevents",
        "lookup_column": "itemid",
        "lookup_value": 51987,
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "value",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": None,
        "note_id_column": None,
    },
    {
        "variable_name": "Nitrat niệu",
        "source_table": "labevents",
        "lookup_column": "itemid",
        "lookup_value": 51487,
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "value",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": None,
        "note_id_column": None,
    },

    # ===== MICROBIOLOGY =====
    {
        "variable_name": "Cấy dịch đường hô hấp",
        "source_table": "microbiology",
        "lookup_column": "spec_type_desc",
        "lookup_value": "BRONCHIAL WASHINGS",
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "org_name",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": None,
        "note_id_column": None,
    },
    {
        "variable_name": "Cấy dịch đường hô hấp",
        "source_table": "microbiology",
        "lookup_column": "spec_type_desc",
        "lookup_value": "BRONCHOALVEOLAR LAVAGE",
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "org_name",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": None,
        "note_id_column": None,
    },
    {
        "variable_name": "Cấy dịch đường hô hấp",
        "source_table": "microbiology",
        "lookup_column": "spec_type_desc",
        "lookup_value": "PLEURAL FLUID",
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "org_name",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": None,
        "note_id_column": None,
    },
    {
        "variable_name": "Cấy dịch đường hô hấp",
        "source_table": "microbiology",
        "lookup_column": "spec_type_desc",
        "lookup_value": "SPUTUM",
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "org_name",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": None,
        "note_id_column": None,
    },
    {
        "variable_name": "Cấy máu",
        "source_table": "microbiology",
        "lookup_column": "spec_type_desc",
        "lookup_value": "BLOOD CULTURE",
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "org_name",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": None,
        "note_id_column": None,
    },
    {
        "variable_name": "Cấy nước tiểu",
        "source_table": "microbiology",
        "lookup_column": "spec_type_desc",
        "lookup_value": "URINE",
        "lookup_operator": "==",
        "secondary_lookup_column": "test_name",
        "secondary_lookup_value": "URINE CULTURE",
        "value_column": "org_name",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": None,
        "note_id_column": None,
    },

    # ===== PROCEDUREEVENTS =====
    {
        "variable_name": "Thời gian thở máy",
        "source_table": "procedureevents",
        "lookup_column": "itemid",
        "lookup_value": 225792,
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "value",
        "time_column": "starttime",
        "endtime_column": "endtime",
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": "stay_id",
        "note_id_column": None,
    },
    {
        "variable_name": "Thời gian đặt catheter TMTT",
        "source_table": "procedureevents",
        "lookup_column": "location",
        "lookup_value": "__CENTRAL_LINE__",
        "lookup_operator": "in_list",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "value",
        "time_column": "starttime",
        "endtime_column": "endtime",
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": "stay_id",
        "note_id_column": None,
    },
    {
        "variable_name": "Thời gian đặt ống thông tiểu",
        "source_table": "procedureevents",
        "lookup_column": "itemid",
        "lookup_value": 229351,
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "value",
        "time_column": "starttime",
        "endtime_column": "endtime",
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": "stay_id",
        "note_id_column": None,
    },

    # ===== DISCHARGE =====
    {
        "variable_name": "Ớn lạnh",
        "source_table": "discharge",
        "lookup_column": None,
        "lookup_value": None,
        "lookup_operator": "keyword_search",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "text",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": None,
        "note_id_column": "note_id",
    },
    {
        "variable_name": "Tiểu gấp",
        "source_table": "discharge",
        "lookup_column": None,
        "lookup_value": None,
        "lookup_operator": "keyword_search",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "text",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": None,
        "note_id_column": "note_id",
    },
    {
        "variable_name": "Tiểu nhiều lần",
        "source_table": "discharge",
        "lookup_column": None,
        "lookup_value": None,
        "lookup_operator": "keyword_search",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "text",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": None,
        "note_id_column": "note_id",
    },
    {
        "variable_name": "Tiểu buốt",
        "source_table": "discharge",
        "lookup_column": None,
        "lookup_value": None,
        "lookup_operator": "keyword_search",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "text",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": None,
        "note_id_column": "note_id",
    },
    {
        "variable_name": "Đau hông sườn",
        "source_table": "discharge",
        "lookup_column": None,
        "lookup_value": None,
        "lookup_operator": "keyword_search",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "text",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": None,
        "note_id_column": "note_id",
    },
    {
        "variable_name": "Đau/ấn đau vùng trên xương mu",
        "source_table": "discharge",
        "lookup_column": None,
        "lookup_value": None,
        "lookup_operator": "keyword_search",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "text",
        "time_column": "charttime",
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": "hadm_id",
        "stay_id_column": None,
        "note_id_column": "note_id",
    },

    # ===== RADIOLOGY =====
    {
        "variable_name": "X-quang ngực",
        "source_table": "radiology",
        "lookup_column": "field_name",
        "lookup_value": "FINDINGS",
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "field_value",
        "time_column": None,
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": None,
        "stay_id_column": None,
        "note_id_column": "note_id",
    },
    {
        "variable_name": "CT scan lồng ngực",
        "source_table": "radiology",
        "lookup_column": "field_name",
        "lookup_value": "FINDINGS",
        "lookup_operator": "==",
        "secondary_lookup_column": None,
        "secondary_lookup_value": None,
        "value_column": "field_value",
        "time_column": None,
        "endtime_column": None,
        "subject_id_column": "subject_id",
        "hadm_id_column": None,
        "stay_id_column": None,
        "note_id_column": "note_id",
    },
]

variable_mapping = pd.DataFrame(mapping_rows)

variable_mapping = variable_mapping.drop_duplicates(
    subset=[
        "variable_name",
        "source_table",
        "lookup_column",
        "lookup_value",
        "lookup_operator",
        "secondary_lookup_column",
        "secondary_lookup_value",
        "value_column",
        "time_column",
        "endtime_column",
        "subject_id_column",
        "hadm_id_column",
        "stay_id_column",
        "note_id_column",
    ]
).reset_index(drop=True)

In [32]:
table_map = {
    "chartevents": chartevent,
    "discharge": discharge,
    "labevents": labevent,
    "microbiology": microbiologyevent,
    "procedureevents": procedureevent,
    "radiology": radiologyevent,
}

keyword_map = {
    "Ớn lạnh": ["chills", "rigors", "shivering", "feeling cold", "cold"],
    "Tiểu gấp": ["urinary urgency", "urgency"],
    "Tiểu nhiều lần": ["urinary frequency", "frequent urination"],
    "Tiểu buốt": ["dysuria", "painful urination", "burning on urination"],
    "Đau hông sườn": ["flank pain", "cva tenderness"],
    "Đau/ấn đau vùng trên xương mu": ["suprapubic pain", "suprapubic tenderness"],
}

central_line_locations = [
    "Left IJ", "Right IJ",
    "Left Subclavian", "Right Subclavian",
    "Left Femoral", "Left Femoral.",
    "Right Femoral", "Right Femoral."
]

def get_variable_data(variable_name, subject_id=None, hadm_id=None, stay_id=None):
    mapping = variable_mapping[
        variable_mapping["variable_name"] == variable_name
    ].copy()

    results = []

    for _, row in mapping.iterrows():
        df = table_map[row["source_table"]].copy()

        if subject_id is not None and row["subject_id_column"] in df.columns:
            df = df[df[row["subject_id_column"]] == subject_id]

        if hadm_id is not None and row["hadm_id_column"] is not None and row["hadm_id_column"] in df.columns:
            df = df[df[row["hadm_id_column"]] == hadm_id]

        if stay_id is not None and row["stay_id_column"] is not None and row["stay_id_column"] in df.columns:
            df = df[df[row["stay_id_column"]] == stay_id]

        if row["lookup_operator"] == "==" and row["lookup_column"] is not None:
            df = df[df[row["lookup_column"]] == row["lookup_value"]]

        elif row["lookup_operator"] == "in_list":
            if row["lookup_column"] == "location" and row["lookup_value"] == "__CENTRAL_LINE__":
                df = df[df["location"].isin(central_line_locations)]

        elif row["lookup_operator"] == "keyword_search":
            keywords = keyword_map.get(variable_name, [])
            if "text" in df.columns and keywords:
                pattern = "|".join(keywords)
                df = df[df["text"].str.contains(pattern, case=False, na=False, regex=True)]

        if row["secondary_lookup_column"] is not None:
            col2 = row["secondary_lookup_column"]
            val2 = row["secondary_lookup_value"]
            if col2 in df.columns:
                df = df[df[col2] == val2]

        df = df.copy()
        df["mapped_variable_name"] = row["variable_name"]
        df["mapped_source_table"] = row["source_table"]
        df["mapped_value_column"] = row["value_column"]
        df["mapped_time_column"] = row["time_column"]
        df["mapped_endtime_column"] = row["endtime_column"]

        results.append(df)

    if not results:
        return pd.DataFrame()

    result = pd.concat(results, ignore_index=True, sort=False)
    result = result.drop_duplicates().reset_index(drop=True)
    return result

In [36]:
get_variable_data("Ho", subject_id=10000690)

,subject_id,hadm_id,stay_id,caregiver_id,charttime,storetime,itemid,value,valuenum,valueuom,warning,mapped_variable_name,mapped_source_table,mapped_value_column,mapped_time_column,mapped_endtime_column
0,10000690,25860671,37081114,8787.0,2150-11-06 08:00:00,2150-11-06 09:42:00,223991,Strong,NaN,NaN,0.0,Ho,chartevents,value,charttime,None
1,10000690,25860671,37081114,8787.0,2150-11-06 12:00:00,2150-11-06 14:16:00,223991,Strong,NaN,NaN,0.0,Ho,chartevents,value,charttime,None
2,10000690,25860671,37081114,9137.0,2150-11-06 16:00:00,2150-11-06 16:21:00,223991,Strong,NaN,NaN,0.0,Ho,chartevents,value,charttime,None
3,10000690,25860671,37081114,17393.0,2150-11-02 20:32:00,2150-11-02 20:33:00,223991,Strong,NaN,NaN,0.0,Ho,chartevents,value,charttime,None
4,10000690,25860671,37081114,17393.0,2150-11-03 00:56:00,2150-11-03 00:58:00,223991,Weak,NaN,NaN,0.0,Ho,chartevents,value,charttime,None
5,10000690,25860671,37081114,17393.0,2150-11-03 04:40:00,2150-11-03 04:43:00,223991,Weak,NaN,NaN,0.0,Ho,chartevents,value,charttime,None
6,10000690,25860671,37081114,33125.0,2150-11-03 08:00:00,2150-11-03 09:10:00,223991,Strong,NaN,NaN,0.0,Ho,chartevents,value,charttime,None
7,10000690,25860671,37081114,33125.0,2150-11-03 12:00:00,2150-11-03 11:59:00,223991,Strong,NaN,NaN,0.0,Ho,chartevents,value,charttime,None
8,10000690,25860671,37081114,33125.0,2150-11-03 16:00:00,2150-11-03 16:36:00,223991,Strong,NaN,NaN,0.0,Ho,chartevents,value,charttime,None
9,10000690,25860671,37081114,8787.0,2150-11-06 08:00:00,2150-11-06 09:42:00,223992,Non-productive,NaN,NaN,0.0,Ho,chartevents,value,charttime,None
10,10000690,25860671,37081114,8787.0,2150-11-06 12:00:00,2150-11-06 14:16:00,223992,Productive,NaN,NaN,0.0,Ho,chartevents,value,charttime,None
11,10000690,25860671,37081114,9137.0,2150-11-06 16:00:00,2150-11-06 16:21:00,223992,Productive,NaN,NaN,0.0,Ho,chartevents,value,charttime,None
12,10000690,25860671,37081114,17393.0,2150-11-02 20:32:00,2150-11-02 20:33:00,223992,Congested,NaN,NaN,0.0,Ho,chartevents,value,charttime,None
13,10000690,25860671,37081114,17393.0,2150-11-03 00:56:00,2150-11-03 00:58:00,223992,Congested,NaN,NaN,0.0,Ho,chartevents,value,charttime,None
14,10000690,25860671,37081114,17393.0,2150-11-03 04:40:00,2150-11-03 04:43:00,223992,Congested,NaN,NaN,0.0,Ho,chartevents,value,charttime,None
15,10000690,25860671,37081114,33125.0,2150-11-03 08:00:00,2150-11-03 09:10:00,223992,Non-productive,NaN,NaN,0.0,Ho,chartevents,value,charttime,None
16,10000690,25860671,37081114,33125.0,2150-11-03 12:00:00,2150-11-03 11:59:00,223992,Non-productive,NaN,NaN,0.0,Ho,chartevents,value,charttime,None
17,10000690,25860671,37081114,33125.0,2150-11-03 16:00:00,2150-11-03 16:36:00,223992,Non-productive,NaN,NaN,0.0,Ho,chartevents,value,charttime,None

In [39]:
import pandas as pd
import numpy as np

# =========================
# 1) Helper
# =========================
def _to_datetime_safe(s):
    return pd.to_datetime(s, errors="coerce")

def _contains_any(series, keywords):
    pattern = "|".join(keywords)
    return series.astype(str).str.contains(pattern, case=False, na=False, regex=True)

# =========================
# 2) VAP check for one subject
# =========================
def check_vap_subject(subject_id, verbose=True):
    # ---------- A. Chartevents ----------
    ce = chartevent[chartevent["subject_id"] == subject_id].copy()
    if not ce.empty:
        ce["charttime"] = _to_datetime_safe(ce["charttime"])

    # Nhiệt độ > 38C
    temp_c = ce[(ce["itemid"] == 223762) & (ce["valuenum"] > 38)].copy()

    # Ho: Cough Effort weak/strong
    cough = ce[
        (ce["itemid"] == 223991) &
        (ce["value"].astype(str).str.lower().isin(["weak", "strong"]))
    ].copy()

    # Đờm mủ: Sputum Color != Clear
    sputum = ce[
        (ce["itemid"] == 224370) &
        (~ce["value"].astype(str).str.lower().eq("clear"))
    ].copy()

    # Nhịp thở > 20
    rr = ce[(ce["itemid"] == 230042) & (ce["valuenum"] > 20)].copy()

    # SpO2 < 94
    spo2 = ce[(ce["itemid"] == 220277) & (ce["valuenum"] < 94)].copy()

    # Có hỗ trợ oxy: O2 Delivery Device != none
    oxygen_support = ce[
        (ce["itemid"] == 226732) &
        (~ce["value"].astype(str).str.lower().eq("none"))
    ].copy()

    # Rale / ran / âm phổi bất thường
    lung_sound_keywords = [
        "bronchial", "crackles", "diminished",
        "exp wheeze", "ins/exp wheeze", "insp wheeze",
        "rhonchi", "tubular"
    ]
    lung_sounds = ce[
        ce["itemid"].isin([223986, 223987, 223988, 223989]) &
        _contains_any(ce["value"], lung_sound_keywords)
    ].copy()

    # ---------- B. Radiology ----------
    rad = radiologyevent[radiologyevent["subject_id"] == subject_id].copy()
    pneumonia_keywords = [
        "pneumonia", "pna", "bronchopneumonia", "consolidation",
        "infiltrate", "infiltration", "opacity", "opacities",
        "ground glass", "ggo", "air bronchogram", "patchy",
        "cloudy", "hazy"
    ]
    if not rad.empty:
        imaging = rad[
            (rad["field_name"].astype(str).str.upper() == "FINDINGS") &
            _contains_any(rad["field_value"], pneumonia_keywords)
        ].copy()
    else:
        imaging = pd.DataFrame()

    # ---------- C. Microbiology ----------
    micro = microbiologyevent[microbiologyevent["subject_id"] == subject_id].copy()
    if not micro.empty:
        micro["charttime"] = _to_datetime_safe(micro["charttime"])

    resp_specimens = [
        "BRONCHIAL WASHINGS",
        "BRONCHOALVEOLAR LAVAGE",
        "PLEURAL FLUID",
        "SPUTUM"
    ]

    resp_culture = micro[
        micro["spec_type_desc"].astype(str).isin(resp_specimens) &
        micro["org_name"].notna()
    ].copy()

    blood_culture = micro[
        micro["spec_type_desc"].astype(str).eq("BLOOD CULTURE") &
        micro["org_name"].notna()
    ].copy()

    # ---------- D. Procedureevents: thở máy ----------
    proc = procedureevent[procedureevent["subject_id"] == subject_id].copy()
    if not proc.empty:
        proc["starttime"] = _to_datetime_safe(proc["starttime"])
        proc["endtime"] = _to_datetime_safe(proc["endtime"])

    vent = proc[proc["itemid"] == 225792].copy()

    # =========================
    # 3) Check by stay_id
    # =========================
    stay_ids = sorted(ce["stay_id"].dropna().unique().tolist()) if not ce.empty else []

    results = []

    for stay_id in stay_ids:
        ce_stay = ce[ce["stay_id"] == stay_id].copy()
        hadm_ids = ce_stay["hadm_id"].dropna().unique().tolist()
        hadm_id = hadm_ids[0] if len(hadm_ids) > 0 else np.nan

        temp_stay = temp_c[temp_c["stay_id"] == stay_id]
        cough_stay = cough[cough["stay_id"] == stay_id]
        sputum_stay = sputum[sputum["stay_id"] == stay_id]
        rr_stay = rr[rr["stay_id"] == stay_id]
        spo2_stay = spo2[spo2["stay_id"] == stay_id]
        oxygen_stay = oxygen_support[oxygen_support["stay_id"] == stay_id]
        lung_stay = lung_sounds[lung_sounds["stay_id"] == stay_id]

        # triệu chứng lâm sàng
        symptom_hits = {
            "fever": not temp_stay.empty,
            "cough": not cough_stay.empty,
            "purulent_sputum": not sputum_stay.empty,
            "tachypnea": not rr_stay.empty,
            "low_spo2": not spo2_stay.empty,
            "oxygen_support": not oxygen_stay.empty,
            "abnormal_lung_sounds": not lung_stay.empty,
        }
        symptom_count = sum(symptom_hits.values())

        # imaging theo hadm_id nếu có thể
        # radiology_detail bạn đưa không có hadm_id/time, nên check ở mức subject
        imaging_positive = not imaging.empty

        # microbiology theo hadm_id nếu có
        if not np.isnan(hadm_id):
            resp_culture_stay = resp_culture[resp_culture["hadm_id"] == hadm_id]
            blood_culture_stay = blood_culture[blood_culture["hadm_id"] == hadm_id]
        else:
            resp_culture_stay = resp_culture.iloc[0:0]
            blood_culture_stay = blood_culture.iloc[0:0]

        micro_positive = (not resp_culture_stay.empty) or (not blood_culture_stay.empty)

        # ventilation >= 2 days before first criterion
        positive_event_times = []

        for df_ in [temp_stay, cough_stay, sputum_stay, rr_stay, spo2_stay, oxygen_stay, lung_stay]:
            if not df_.empty and "charttime" in df_.columns:
                positive_event_times.extend(df_["charttime"].dropna().tolist())

        first_criterion_time = min(positive_event_times) if len(positive_event_times) > 0 else pd.NaT

        vent_stay = vent[vent["stay_id"] == stay_id].copy()
        ventilation_ok = False

        if pd.notna(first_criterion_time) and not vent_stay.empty:
            for _, r in vent_stay.iterrows():
                st = r["starttime"]
                if pd.isna(st):
                    continue
                # đặt thở máy trước ít nhất 2 ngày
                if st <= first_criterion_time - pd.Timedelta(days=2):
                    ventilation_ok = True
                    break

        # rule gần đúng:
        # (>=2 triệu chứng) + imaging + ventilation
        # hoặc (>=3 triệu chứng) + ventilation
        vap_flag = (
            ((symptom_count >= 2) and imaging_positive and ventilation_ok) or
            ((symptom_count >= 3) and ventilation_ok) or
            ((symptom_count >= 2) and micro_positive and ventilation_ok)
        )

        results.append({
            "subject_id": subject_id,
            "hadm_id": hadm_id,
            "stay_id": stay_id,
            "symptom_count": symptom_count,
            "fever": symptom_hits["fever"],
            "cough": symptom_hits["cough"],
            "purulent_sputum": symptom_hits["purulent_sputum"],
            "tachypnea": symptom_hits["tachypnea"],
            "low_spo2": symptom_hits["low_spo2"],
            "oxygen_support": symptom_hits["oxygen_support"],
            "abnormal_lung_sounds": symptom_hits["abnormal_lung_sounds"],
            "imaging_positive": imaging_positive,
            "resp_culture_positive": not resp_culture_stay.empty,
            "blood_culture_positive": not blood_culture_stay.empty,
            "ventilation_ok_ge_2d_before_first_criterion": ventilation_ok,
            "first_criterion_time": first_criterion_time,
            "vap_suspected": vap_flag,
        })

    result_df = pd.DataFrame(results).sort_values(["stay_id"])

    if verbose:
        print("=== VAP check ===")
        print(result_df)

    return result_df

In [41]:
vap_result = check_vap_subject(10000690)

=== VAP check ===
   subject_id   hadm_id   stay_id  symptom_count  fever  cough  \
0    10000690  25860671  37081114              5  False   True

   purulent_sputum  tachypnea  low_spo2  oxygen_support  abnormal_lung_sounds  \
0             True      False      True            True                  True

   imaging_positive  resp_culture_positive  blood_culture_positive  \
0             False                  False                   False

   ventilation_ok_ge_2d_before_first_criterion first_criterion_time  \
0                                        False  2150-11-02 19:40:00

   vap_suspected
0          False